ktor {
  deployment {
    port = 8080
    port = ${?PORT}
  }
  application {
    modules = [ com.sashaflake.ApplicationKt.module ]
  }
}

jwt {
  secret = "change-me-in-production"
  secret = ${?JWT_SECRET}
  issuer = "auth-service"
  audience = "auth-service-users"
}

dragonfly {
  uri = "redis://localhost:6379"
  uri = ${?DRAGONFLY_URI}
}

storage {
  inMemory = false
  inMemory = ${?STORAGE_IN_MEMORY}
}
