import { useMemo } from 'react'
import { useForm } from '@tanstack/react-form'
import { Equivalence, Array as A } from 'effect'
import { schemaValidator } from '@/shared/form/schemaResolver.domain'
import { RuleFormSchema } from '../domain/routing-rules.dto'
import type { RoutingRule, RuleFormValues, DestinationDraft } from '../domain/routing-rules.types'
import { DestinationDraftEq } from '../domain/routing-rules.types'

// ── Helpers (pure) ────────────────────────────────────────────────────────────

/**
 * Converts an existing {@link RoutingRule} into editable form values.
 *
 * Destination IDs are generated by the supplied factory because the backend
 * model does not expose per-destination client-side identifiers.
 *
 * @param rule        - Existing rule to edit
 * @param generateId  - Factory that returns a fresh identifier
 * @returns Editable form values seeded from the rule (see {@link RuleFormValues})
 * @sideEffects none
 */
const toFormValues = (
  rule: RoutingRule,
  generateId: () => string,
): RuleFormValues => ({
  name:         rule.name,
  priority:     rule.priority,
  match:        rule.match,
  destinations: rule.destinations.map(
    ({ serviceId, version, weightPct }): DestinationDraft => ({
      id:        generateId(),
      serviceId,
      version,
      weightPct,
    })
  ),
})

/**
 * Default form values for creating a new routing rule.
 *
 * @returns Fresh {@link RuleFormValues} with empty name, priority 100,
 *          empty match, and no destinations
 * @sideEffects none
 */
const defaultValues = (): RuleFormValues => ({
  name:         '',
  priority:     100,
  match:        {},
  destinations: [],
})

/**
 * Equivalence relation for complete rule form values.
 *
 * Compares primitive fields and zips destinations to compare them with
 * {@link DestinationDraftEq}.
 *
 * @sideEffects none
 */
const RuleFormEq: Equivalence.Equivalence<RuleFormValues> = Equivalence.make((a, b) =>
  a.name === b.name &&
  a.priority === b.priority &&
  a.match.pathPrefix === b.match.pathPrefix &&
  a.destinations.length === b.destinations.length &&
  A.zip(a.destinations, b.destinations).every(([da, db]) => DestinationDraftEq(da, db))
)

/**
 * Synchronous validator built from {@link RuleFormSchema}.
 *
 * @sideEffects none
 */
const validate = schemaValidator(RuleFormSchema)

// ── Hook ──────────────────────────────────────────────────────────────────────

/**
 * Props accepted by {@link useRuleForm}.
 */
export type UseRuleFormInput = {
  /** Existing rule to populate the form, or `undefined` for creation. */
  initial: RoutingRule | undefined

  /** Callback invoked with validated form values on submit. */
  onSubmit: (values: RuleFormValues) => void
}

/**
 * Hook that manages the create/edit rule form.
 *
 * Wires `@tanstack/react-form` to Effect's {@link RuleFormSchema} for
 * validation and tracks dirty state with an equivalence relation so the
 * discard confirmation only appears when the user has actually changed
 * something.
 *
 * @param initial  - Existing rule or `undefined`
 * @param onSubmit - Submit callback
 * @returns `{ form, isDirty, fieldError }` for use by {@link RuleFormModal}
 * @sideEffects Creates a TanStack Form instance; calls `crypto.randomUUID()`
 *              via the injected ID factory when converting an existing rule.
 */
// Explicit return type breaks TanStack Form generic inference for `form.Field`,
// causing every field to resolve to `any`. Inference is therefore preserved here.
// eslint-disable-next-line @typescript-eslint/explicit-function-return-type
export function useRuleForm(
  initial: RoutingRule | undefined,
  onSubmit: (values: RuleFormValues) => void,
) {
  const initialValues = useMemo(
    () => (initial ? toFormValues(initial, () => crypto.randomUUID()) : defaultValues()),
    // eslint-disable-next-line reactHooks/exhaustive-deps
    [initial?.id],
  )

  const form = useForm({
    defaultValues: initialValues,
    onSubmit: ({ value }) => onSubmit(value),
  })

  const isDirty = useMemo(
    () => !RuleFormEq(form.state.values, initialValues),
    [form.state.values, initialValues],
  )

  const fieldError = (field: string): string | undefined => {
    if (!form.state.isSubmitted && !form.state.isTouched) return undefined
    const errors = validate(form.state.values)
    return errors.find(e => e.field === field)?.message
  }

  return { form, isDirty, fieldError }
}
